language: python

install:
  - pip install matplotlib
python:
 - 3.6
 - 3.5
 - 3.7

before_install:
 - wget https://github.com/Bobbycookie/Python_Class_Concordia/blob/master/breast_cancer.txt
 

script:
 - python3 ll_p3.py breast_cancer.txt R --cols Class
 - python3 ll_p3.py breast_cancer.txt P --cols Adhesion Cell-Size Class
 - python3 ll_p3.py breast_cancer.txt P --cols Adhesion Cell-Shape Class
 - python3 ll_p3.py breast_cancer.txt P --cols Adhesion Nucleoli Class